### ISSUE TITLE
Support for India

### ISSUE THREAD

**Issue by abhyuday-tripathi** [RIAEvangelist/node-dominos-pizza-api#108] opened 2021-03-26 11:51 UTC
# I have tried using this api from India but it's not working 

Please add the code for India and The new Dominos Website 

Abhyuday Tripathi

**Comment by abhyuday-tripathi** [comment] 2021-03-26 11:51
Please give the code for complete India support

**Comment by RIAEvangelist** [comment] 2021-04-03 16:19
I have documented how to add support for other countries, would you send me the API endpoints so I can add them in?

I would really love to add support for India, but either I need a flight to India to do it on my own, or we all need help from a contributor in India. Could you be that contributor that works with me to make it happen?

The docs on international support can be found here : [docs/International Support](https://github.com/RIAEvangelist/node-dominos-pizza-api/blob/master/docs/InternationalSupport.md)

**Comment by RIAEvangelist** [comment] 2021-04-03 16:23
This is also a duplicate of #2 which has some information that could help you or one of your friends. Please do help us all by contributing the International URLs to me. Even if you just share the JSON object with the links like the documentation shows, I can integrate it in for everyone to use.

The world of Pizza lovers would thank you.

**Closed by RIAEvangelist** 2021-04-03 16:23 UTC
Labels: enhancement, help wanted

**Comment by abhyuday-tripathi** [comment] 2021-04-05 14:57
I would really love to help you with the India api endpoints, can you Tell me how to Share you the URLs?

**Comment by abhyuday-tripathi** [comment] 2021-04-05 15:00
Should I add those here??

**Comment by abhyuday-tripathi** [comment] 2021-04-05 15:37
Hey, here is the URL for all the stores available in India - [STORES_URL](https://api.dominos.co.in/locator-service/ve2/stores)

I am digging out for more URLs I will add those ASAP

**Comment by abhyuday-tripathi** [comment] 2021-04-05 15:42
I found this URL for the menu

The URL is here - [MENU_URL](https://api.dominos.co.in/prod-olo-api/v1/67250/menu/data)
